version: 0.0.0+{build}

skip_tags: true

matrix:
  fast_finish: true

environment:
  NVM_HOME: C:\Users\appveyor\AppData\Roaming\nvm
  POWERSHELL_GALLERY_API_KEY:
    secure: Y7B8n8Ott858qlg1xt1Kz7VnvR59aO963p5dquIEQsMUZpvK/Ip5Rmj7G/jBKM6r
  GITHUB_ACCESS_TOKEN:
    secure: cEpuAn4TbJ17Y4WMMsHj46T4DLFMGE4n7xafkbiVQL4jueqc9TGG7NHWg4qbwmt7
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    LANG: us_US.UTF-8
    APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5mBnjgF/1nuWMj2pTdbk7mre5U9Q8OpCuWQAfjzx2Pf+7EskomFhleCWnATNqrmDw8Y8H9YtK8pcaLHudFbQwAxJ9WjCYsiQ2hOq22BLYVh0/e2JRiV8d6ODYBA//Q8/Gu4iz6AV+0QHSWATtuDXJisN/+ak8qF9wU8TqAro4C7tMq+bi4vR00c+vzvokXLN9RQaRKmGm9sixTQsAA9JLWiLB8Hir588Sn+9yysGwcZ/NcwX8GX6bszW4/5XP/kImMUpv5JeSkNrob/exv9zsLAVVLDviqNJCOPUu16Y9xBaGtpXbUn/wVqbON6hv74wKrEsHegvE8IYEm0HziH7Z ajensen@04-PC0NXXGR
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
- sh: export APPVEYOR_SSH_BLOCK=true
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
- pwsh: >-
    # $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    
    # On Linux, progress bars still show when running on the build server and take *ages* to render and they screw up the displayed output.
    $ProgressPreference = 'SilentlyContinue'
    
    .\build.ps1 -Verbose

test: off

artifacts:
- path: .output\pester*.xml
  name: TestResults
- path: .output\*.zip
  name: Packages
- path: .output\msbuild.*.log

notifications:
- provider: Email
  to:
  - aaron@splatteredbits.com
  - ajensen@webmd.net
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false